### ISSUE TITLE
Meeting with the mentors! 

### ISSUE THREAD

**Issue by samanthavenialogan** [animeshk08/chaoss-microtasks#12]
Hey Animeshk08, 

Thanks so much for your amazing level of communication! I'm just leaving this to let you know that we are going to have a meeting here in a few days to give you a chance to meet us, ask some questions, and other stuff prior to your application which is due relatively soon. This is a relatively unique GSoC opportunity so we thought this would be helpful :) 

We've chosen to have the meeting at 12:30pm, Thursday GMT, (6:30am Wednesday MST or 7:00pm thursday, IST) on the CHAOSS meeting room here:

https://unomaha.zoom.us/j/720431288   

Please check your local time and keep in mind daylight savings recently happened in the USA.

If you can't make it, you can also respond on the CHAOSS mailing list or email me directly at samantha@sociallyconstructed.online so we can set up a meeting with you ^^.  

We hope to see you there, we can't wait to work with you, and we hope you'll stay safe wherever you are.

Samantha Venia Logan
Co-Founder of SociallyConstructed.Online307-274-5516  | samantha@SociallyConstructed.Online
6715 Autumn Ridge Dr. Unit 2, Fort Collins CO., 80525

**Comment by animeshk08** [comment]
Hi, @samanthavenialogan Thank you so much for this opportunity and considering our local time while scheduling the meet!! I am looking forward to meeting the mentors and discussing more about this project :)

**Comment by animeshk08** [comment]
Closing this issue. Please feel free to re-open it if needed :)
